<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260908113916 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE advertising_space CHANGE daily_price daily_price NUMERIC(12, 2) DEFAULT \'0\' NOT NULL');
        $this->addSql('ALTER TABLE application ADD CONSTRAINT FK_A45BDDC1A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE appointment CHANGE meta meta JSON DEFAULT NULL');
        $this->addSql('ALTER TABLE booste_annonce ADD CONSTRAINT FK_A6E4B65BA76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE booste_annonce RENAME INDEX uniq_booste_annonce_reference TO UNIQ_A6E4B65BAEA34913');
        $this->addSql('ALTER TABLE booste_annonce RENAME INDEX idx_booste_annonce_annonce TO IDX_A6E4B65B8805AB2F');
        $this->addSql('ALTER TABLE booste_annonce RENAME INDEX idx_booste_annonce_user TO IDX_A6E4B65BA76ED395');
        $this->addSql('ALTER TABLE calendrier ADD CONSTRAINT FK_B2753CB9F675F31B FOREIGN KEY (author_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE calendrier ADD CONSTRAINT FK_B2753CB918777CEF FOREIGN KEY (talent_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE calendrier ADD CONSTRAINT FK_B2753CB9BE04EA9 FOREIGN KEY (job_id) REFERENCES job (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE calendrier ADD CONSTRAINT FK_B2753CB93E030ACD FOREIGN KEY (application_id) REFERENCES application (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE call_session CHANGE meta meta JSON DEFAULT NULL');
        $this->addSql('ALTER TABLE call_signal CHANGE payload payload JSON DEFAULT NULL, CHANGE created_at created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE call_signal ADD CONSTRAINT FK_B1D444D745A0AD45 FOREIGN KEY (call_session_id) REFERENCES call_session (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE call_signal ADD CONSTRAINT FK_B1D444D7F624B39D FOREIGN KEY (sender_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('CREATE INDEX IDX_B1D444D745A0AD45 ON call_signal (call_session_id)');
        $this->addSql('ALTER TABLE call_signal RENAME INDEX idx_call_signal_sender TO IDX_B1D444D7F624B39D');
        $this->addSql('ALTER TABLE chat_group ADD CONSTRAINT FK_6CBDA95E7E3C61F9 FOREIGN KEY (owner_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE chat_group_join_request ADD CONSTRAINT FK_FA9EE464CA760E77 FOREIGN KEY (chat_group_id) REFERENCES chat_group (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE chat_group_join_request ADD CONSTRAINT FK_FA9EE464ED442CF4 FOREIGN KEY (requester_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE chat_group_join_request ADD CONSTRAINT FK_FA9EE464FC6B21F1 FOREIGN KEY (reviewed_by_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE chat_group_member ADD CONSTRAINT FK_5D894B29CA760E77 FOREIGN KEY (chat_group_id) REFERENCES chat_group (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE chat_group_member ADD CONSTRAINT FK_5D894B29A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE chat_group_message CHANGE meta meta JSON NOT NULL');
        $this->addSql('ALTER TABLE chat_group_message_reaction ADD CONSTRAINT FK_41BC1778537A1329 FOREIGN KEY (message_id) REFERENCES chat_group_message (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE chat_group_message_reaction ADD CONSTRAINT FK_41BC1778A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE chat_group_recommendation ADD CONSTRAINT FK_D18764AFCA760E77 FOREIGN KEY (chat_group_id) REFERENCES chat_group (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE chat_group_recommendation ADD CONSTRAINT FK_D18764AFD59A4918 FOREIGN KEY (recommended_by_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE chat_group_recommendation ADD CONSTRAINT FK_D18764AF4F482379 FOREIGN KEY (recommended_to_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE chat_test_message CHANGE settings_snapshot settings_snapshot JSON NOT NULL');
        $this->addSql('DROP INDEX IDX_CHAT_TYPING_UPDATED ON chat_typing_state');
        $this->addSql('ALTER TABLE chat_typing_state CHANGE typing typing TINYINT(1) NOT NULL, CHANGE updated_at updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE chat_typing_state ADD CONSTRAINT FK_328D94529AC0396 FOREIGN KEY (conversation_id) REFERENCES conversation (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE chat_typing_state ADD CONSTRAINT FK_328D9452A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('CREATE INDEX IDX_328D94529AC0396 ON chat_typing_state (conversation_id)');
        $this->addSql('ALTER TABLE chat_typing_state RENAME INDEX idx_chat_typing_user TO IDX_328D9452A76ED395');
        $this->addSql('ALTER TABLE company_kyc_case ADD CONSTRAINT FK_E4AB80E7979B1AD6 FOREIGN KEY (company_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE company_kyc_case ADD CONSTRAINT FK_E4AB80E7FC6B21F1 FOREIGN KEY (reviewed_by_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE company_kyc_document ADD CONSTRAINT FK_73C7CC1AA9BA5942 FOREIGN KEY (kyc_case_id) REFERENCES company_kyc_case (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE company_kyc_review ADD CONSTRAINT FK_687B158AA9BA5942 FOREIGN KEY (kyc_case_id) REFERENCES company_kyc_case (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE company_kyc_review ADD CONSTRAINT FK_687B158A70574616 FOREIGN KEY (reviewer_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE contact_log ADD CONSTRAINT FK_720509FDA76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE contact_log ADD CONSTRAINT FK_720509FD6C066AFE FOREIGN KEY (target_user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE contact_log RENAME INDEX idx_contact_log_ticket TO IDX_720509FD700047D2');
        $this->addSql('ALTER TABLE contact_ticket RENAME INDEX uniq_contact_ticket_payment TO UNIQ_7329A224C3A3BB');
        $this->addSql('ALTER TABLE contact_ticket RENAME INDEX idx_contact_ticket_user TO IDX_7329A22A76ED395');
        $this->addSql('ALTER TABLE contact_ticket RENAME INDEX idx_contact_ticket_profession TO IDX_7329A22FDEF8996');
        $this->addSql('ALTER TABLE conversation ADD CONSTRAINT FK_8A8E26E9EF6A4166 FOREIGN KEY (participant_a_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE conversation ADD CONSTRAINT FK_8A8E26E9FDDFEE88 FOREIGN KEY (participant_b_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE conversation ADD CONSTRAINT FK_8A8E26E9FB976A01 FOREIGN KEY (professional_profile_id) REFERENCES professional_profile (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE deliverable ADD CONSTRAINT FK_A17DA4417E3C61F9 FOREIGN KEY (owner_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE deliverable ADD CONSTRAINT FK_A17DA441C69DE5E5 FOREIGN KEY (validated_by_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('DROP INDEX idx_document_grant_owner_status ON document_access_grant');
        $this->addSql('DROP INDEX idx_document_grant_viewer_status ON document_access_grant');
        $this->addSql('ALTER TABLE document_access_grant CHANGE status status VARCHAR(20) NOT NULL, CHANGE requested_at requested_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', CHANGE decided_at decided_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', CHANGE expires_at expires_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', CHANGE last_access_at last_access_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE document_access_grant ADD CONSTRAINT FK_8D753B6E7E3C61F9 FOREIGN KEY (owner_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE document_access_grant ADD CONSTRAINT FK_8D753B6E6C59C752 FOREIGN KEY (viewer_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('CREATE INDEX IDX_8D753B6E7E3C61F9 ON document_access_grant (owner_id)');
        $this->addSql('CREATE INDEX IDX_8D753B6E6C59C752 ON document_access_grant (viewer_id)');
        $this->addSql('ALTER TABLE email_verifications ADD CONSTRAINT FK_7EB1F4EEA76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE favori_job ADD CONSTRAINT FK_2695B255A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE favori_job ADD CONSTRAINT FK_2695B255BE04EA9 FOREIGN KEY (job_id) REFERENCES job (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE favorite ADD CONSTRAINT FK_68C58ED9A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE favorite ADD CONSTRAINT FK_68C58ED96C066AFE FOREIGN KEY (target_user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE friendship ADD CONSTRAINT FK_7234A45FED442CF4 FOREIGN KEY (requester_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE friendship ADD CONSTRAINT FK_7234A45F2261B4C3 FOREIGN KEY (addressee_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE friendship ADD CONSTRAINT FK_7234A45F1DA661F8 FOREIGN KEY (blocked_by_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE incident CHANGE status status VARCHAR(20) NOT NULL, CHANGE severity severity VARCHAR(20) NOT NULL, CHANGE trace trace JSON DEFAULT NULL, CHANGE context context JSON DEFAULT NULL, CHANGE occurrence_count occurrence_count INT NOT NULL, CHANGE created_at created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', CHANGE last_occurred_at last_occurred_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', CHANGE resolved_at resolved_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE incident ADD CONSTRAINT FK_3D03A11AA76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE incident RENAME INDEX uniq_incident_reference TO UNIQ_3D03A11AAEA34913');
        $this->addSql('ALTER TABLE incident RENAME INDEX idx_incident_user TO IDX_3D03A11AA76ED395');
        $this->addSql('ALTER TABLE invoices ADD CONSTRAINT FK_6A2F2F95A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE invoices ADD CONSTRAINT FK_6A2F2F954C3A3BB FOREIGN KEY (payment_id) REFERENCES payment (id)');
        $this->addSql('DROP INDEX IDX_FBD8E0F845E283F4 ON job');
        $this->addSql('ALTER TABLE job DROP urgence_job_id, CHANGE created_by_id created_by_id INT NOT NULL');
        $this->addSql('ALTER TABLE job ADD CONSTRAINT FK_FBD8E0F86BF700BD FOREIGN KEY (status_id) REFERENCES status_job (id)');
        $this->addSql('ALTER TABLE job ADD CONSTRAINT FK_FBD8E0F828372591 FOREIGN KEY (type_job_id) REFERENCES type_job (id)');
        $this->addSql('ALTER TABLE job ADD CONSTRAINT FK_FBD8E0F8FDEF8996 FOREIGN KEY (profession_id) REFERENCES profession (id)');
        $this->addSql('ALTER TABLE job ADD CONSTRAINT FK_FBD8E0F8B03A8386 FOREIGN KEY (created_by_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE job ADD CONSTRAINT FK_FBD8E0F869F4B775 FOREIGN KEY (verified_by_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE job ADD CONSTRAINT FK_FBD8E0F838E2DD21 FOREIGN KEY (modified_by_admin_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE job_view ADD CONSTRAINT FK_7931DDCFA76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE job_view ADD CONSTRAINT FK_7931DDCFBE04EA9 FOREIGN KEY (job_id) REFERENCES job (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE kyc_rule CHANGE meta meta JSON DEFAULT NULL');
        $this->addSql('ALTER TABLE message CHANGE meta meta JSON DEFAULT NULL');
        $this->addSql('ALTER TABLE message_reaction ADD CONSTRAINT FK_ADF1C3E6537A1329 FOREIGN KEY (message_id) REFERENCES message (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE message_reaction ADD CONSTRAINT FK_ADF1C3E6A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('DROP INDEX IDX_ALERT_ACTIVE_PROFESSION ON newsletter_subscriber');
        $this->addSql('ALTER TABLE newsletter_subscriber CHANGE email email VARCHAR(180) NOT NULL');
        $this->addSql('ALTER TABLE newsletter_subscriber RENAME INDEX idx_alert_profession TO IDX_401562C3FDEF8996');
        $this->addSql('ALTER TABLE newsletter_subscriber RENAME INDEX idx_alert_user TO IDX_401562C3A76ED395');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT FK_BF5476CAA76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE payment ADD CONSTRAINT FK_6D28840DA76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE payment ADD CONSTRAINT FK_6D28840D9A1887DC FOREIGN KEY (subscription_id) REFERENCES subscription (id)');
        $this->addSql('ALTER TABLE payment ADD CONSTRAINT FK_6D28840DA53A8AA FOREIGN KEY (provider_id) REFERENCES provider (id)');
        $this->addSql('ALTER TABLE payment ADD CONSTRAINT FK_6D28840D590473D FOREIGN KEY (status_payment_id) REFERENCES status_payment (id)');
        $this->addSql('ALTER TABLE payment_dispute ADD CONSTRAINT FK_25DB5EEDA76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE payment_dispute ADD CONSTRAINT FK_25DB5EED4C3A3BB FOREIGN KEY (payment_id) REFERENCES payment (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE payment_dispute ADD CONSTRAINT FK_25DB5EED2989F1FD FOREIGN KEY (invoice_id) REFERENCES invoices (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE payment_dispute ADD CONSTRAINT FK_25DB5EEDFE65AF40 FOREIGN KEY (handled_by_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE personal_profile ADD CONSTRAINT FK_270A324448F3B3C FOREIGN KEY (sexe_id) REFERENCES sexe (id)');
        $this->addSql('ALTER TABLE personal_profile ADD CONSTRAINT FK_270A324A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE personal_profile ADD CONSTRAINT FK_270A324DEF31FA3 FOREIGN KEY (cni_verified_by_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE plan CHANGE features features JSON DEFAULT NULL');
        $this->addSql('ALTER TABLE plan_duration ADD CONSTRAINT FK_883AB7BAE899029B FOREIGN KEY (plan_id) REFERENCES plan (id)');
        $this->addSql('ALTER TABLE profession ADD CONSTRAINT FK_BA930D69BCF5E72D FOREIGN KEY (categorie_id) REFERENCES categorie (id)');
        $this->addSql('ALTER TABLE professional_media ADD CONSTRAINT FK_B551BE6FB976A01 FOREIGN KEY (professional_profile_id) REFERENCES professional_profile (id)');
        $this->addSql('ALTER TABLE professional_profile ADD CONSTRAINT FK_E728A82FDEF8996 FOREIGN KEY (profession_id) REFERENCES profession (id)');
        $this->addSql('ALTER TABLE professional_profile ADD CONSTRAINT FK_E728A82CDA9F63E FOREIGN KEY (status_profile_id) REFERENCES status_profile (id)');
        $this->addSql('ALTER TABLE professional_profile ADD CONSTRAINT FK_E728A82A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE professional_profile ADD CONSTRAINT FK_E728A8269F4B775 FOREIGN KEY (verified_by_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE professional_profile_profession_skill ADD CONSTRAINT FK_6E2CE0BAFB976A01 FOREIGN KEY (professional_profile_id) REFERENCES professional_profile (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE professional_profile_profession_skill ADD CONSTRAINT FK_6E2CE0BAFDEF8996 FOREIGN KEY (profession_id) REFERENCES profession (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE profile_view ADD CONSTRAINT FK_4835241A6C59C752 FOREIGN KEY (viewer_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE profile_view ADD CONSTRAINT FK_4835241AFB976A01 FOREIGN KEY (professional_profile_id) REFERENCES professional_profile (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE rating ADD CONSTRAINT FK_D8892622A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE rating ADD CONSTRAINT FK_D889262237F12F38 FOREIGN KEY (rating_by_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE report ADD CONSTRAINT FK_C42F7784E1CFE6F5 FOREIGN KEY (reporter_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE report ADD CONSTRAINT FK_C42F77846C066AFE FOREIGN KEY (target_user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE report ADD CONSTRAINT FK_C42F7784FE65AF40 FOREIGN KEY (handled_by_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE report ADD CONSTRAINT FK_C42F7784BCF5E72D FOREIGN KEY (categorie_id) REFERENCES categorie_report (id)');
        $this->addSql('ALTER TABLE report_job ADD CONSTRAINT FK_B23987FBE04EA9 FOREIGN KEY (job_id) REFERENCES job (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE report_job ADD CONSTRAINT FK_B23987FA76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE report_job ADD CONSTRAINT FK_B23987FBCF5E72D FOREIGN KEY (categorie_id) REFERENCES categorie_report (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE review ADD CONSTRAINT FK_794381C6F675F31B FOREIGN KEY (author_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE review ADD CONSTRAINT FK_794381C6158E0B66 FOREIGN KEY (target_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE review ADD CONSTRAINT FK_794381C6BE04EA9 FOREIGN KEY (job_id) REFERENCES job (id)');
        $this->addSql('ALTER TABLE review_score ADD CONSTRAINT FK_21171B4A3E2E969B FOREIGN KEY (review_id) REFERENCES review (id)');
        $this->addSql('ALTER TABLE review_score ADD CONSTRAINT FK_21171B4A990BEA15 FOREIGN KEY (criteria_id) REFERENCES review_criteria (id)');
        $this->addSql('ALTER TABLE role_definition_permission ADD CONSTRAINT FK_1672C7AC5EEF6182 FOREIGN KEY (role_definition_id) REFERENCES role_definition (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE role_definition_permission ADD CONSTRAINT FK_1672C7AC7730B2D4 FOREIGN KEY (security_permission_id) REFERENCES security_permission (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE sanction ADD CONSTRAINT FK_6D6491AFA76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE sanction ADD CONSTRAINT FK_6D6491AFB03A8386 FOREIGN KEY (created_by_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE security_event CHANGE payload_json payload_json JSON DEFAULT NULL');
        $this->addSql('ALTER TABLE security_incident CHANGE metadata metadata JSON DEFAULT NULL');
        $this->addSql('ALTER TABLE subscription ADD CONSTRAINT FK_A3C664D3A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE subscription ADD CONSTRAINT FK_A3C664D3E899029B FOREIGN KEY (plan_id) REFERENCES plan (id)');
        $this->addSql('ALTER TABLE subscription ADD CONSTRAINT FK_A3C664D36BF700BD FOREIGN KEY (status_id) REFERENCES status_subscription (id)');
        $this->addSql('ALTER TABLE support_ticket ADD CONSTRAINT FK_1F5A4D53BBB3772B FOREIGN KEY (customer_user_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE support_ticket ADD CONSTRAINT FK_1F5A4D53F4BD7827 FOREIGN KEY (assigned_to_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE talent_availability ADD CONSTRAINT FK_D0C49398FB976A01 FOREIGN KEY (professional_profile_id) REFERENCES professional_profile (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user CHANGE roles roles JSON NOT NULL');
        $this->addSql('ALTER TABLE user ADD CONSTRAINT FK_8D93D64946032730 FOREIGN KEY (type_compte_id) REFERENCES type_compte (id)');
        $this->addSql('ALTER TABLE user ADD CONSTRAINT FK_8D93D649F92F3E70 FOREIGN KEY (country_id) REFERENCES country (id)');
        $this->addSql('ALTER TABLE user RENAME INDEX uniq_user_facebook_id TO UNIQ_8D93D6499BE8FD98');
        $this->addSql('ALTER TABLE user RENAME INDEX uniq_user_apple_id TO UNIQ_8D93D649571323F9');
        $this->addSql('ALTER TABLE user RENAME INDEX uniq_user_microsoft_id TO UNIQ_8D93D64944F23B3E');
        $this->addSql('ALTER TABLE user_activity_log CHANGE meta meta JSON NOT NULL');
        $this->addSql('ALTER TABLE user_log ADD CONSTRAINT FK_6429094EA76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE user_log ADD CONSTRAINT FK_6429094E4FFA550E FOREIGN KEY (device_type_id) REFERENCES device_type (id)');
        $this->addSql('ALTER TABLE user_log ADD CONSTRAINT FK_6429094EA391D4AD FOREIGN KEY (operating_system_id) REFERENCES operating_system (id)');
        $this->addSql('ALTER TABLE user_log ADD CONSTRAINT FK_6429094E4C9BF8BD FOREIGN KEY (browser_id) REFERENCES browser (id)');
        $this->addSql('ALTER TABLE user_log ADD CONSTRAINT FK_6429094EF92F3E70 FOREIGN KEY (country_id) REFERENCES country (id)');
        $this->addSql('ALTER TABLE user_setting CHANGE notifications notifications JSON NOT NULL');
        $this->addSql('ALTER TABLE user_two_factor CHANGE backup_codes backup_codes JSON DEFAULT NULL');
        $this->addSql('ALTER TABLE watchlist_item ADD CONSTRAINT FK_1DEA83F66C066AFE FOREIGN KEY (target_user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE watchlist_item ADD CONSTRAINT FK_1DEA83F6B03A8386 FOREIGN KEY (created_by_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE webhook_delivery ADD CONSTRAINT FK_C97B6A3821AF7E36 FOREIGN KEY (endpoint_id) REFERENCES webhook_endpoint (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE admin_audit_log DROP FOREIGN KEY FK_1F16C5C76352511C');
        $this->addSql('ALTER TABLE advertising_space CHANGE daily_price daily_price NUMERIC(12, 2) DEFAULT \'0.00\' NOT NULL');
        $this->addSql('ALTER TABLE application DROP FOREIGN KEY FK_A45BDDC1A76ED395');
        $this->addSql('ALTER TABLE appointment DROP FOREIGN KEY FK_FE38F844CC3D5E73');
        $this->addSql('ALTER TABLE appointment DROP FOREIGN KEY FK_FE38F84418777CEF');
        $this->addSql('ALTER TABLE appointment DROP FOREIGN KEY FK_FE38F844BE04EA9');
        $this->addSql('ALTER TABLE appointment DROP FOREIGN KEY FK_FE38F8443E030ACD');
        $this->addSql('ALTER TABLE appointment DROP FOREIGN KEY FK_FE38F8449AC0396');
        $this->addSql('ALTER TABLE appointment DROP FOREIGN KEY FK_FE38F8441418957');
        $this->addSql('ALTER TABLE appointment CHANGE meta meta LONGTEXT DEFAULT NULL COLLATE `utf8mb4_bin`');
        $this->addSql('ALTER TABLE booste_annonce DROP FOREIGN KEY FK_A6E4B65BA76ED395');
        $this->addSql('ALTER TABLE booste_annonce RENAME INDEX idx_a6e4b65b8805ab2f TO IDX_BOOSTE_ANNONCE_ANNONCE');
        $this->addSql('ALTER TABLE booste_annonce RENAME INDEX idx_a6e4b65ba76ed395 TO IDX_BOOSTE_ANNONCE_USER');
        $this->addSql('ALTER TABLE booste_annonce RENAME INDEX uniq_a6e4b65baea34913 TO UNIQ_BOOSTE_ANNONCE_REFERENCE');
        $this->addSql('ALTER TABLE calendrier DROP FOREIGN KEY FK_B2753CB9F675F31B');
        $this->addSql('ALTER TABLE calendrier DROP FOREIGN KEY FK_B2753CB918777CEF');
        $this->addSql('ALTER TABLE calendrier DROP FOREIGN KEY FK_B2753CB9BE04EA9');
        $this->addSql('ALTER TABLE calendrier DROP FOREIGN KEY FK_B2753CB93E030ACD');
        $this->addSql('ALTER TABLE call_session DROP FOREIGN KEY FK_5E14CE19AC0396');
        $this->addSql('ALTER TABLE call_session DROP FOREIGN KEY FK_5E14CE1A5626C52');
        $this->addSql('ALTER TABLE call_session DROP FOREIGN KEY FK_5E14CE168AC0374');
        $this->addSql('ALTER TABLE call_session CHANGE meta meta LONGTEXT DEFAULT NULL COLLATE `utf8mb4_bin`');
        $this->addSql('ALTER TABLE call_signal DROP FOREIGN KEY FK_B1D444D745A0AD45');
        $this->addSql('ALTER TABLE call_signal DROP FOREIGN KEY FK_B1D444D7F624B39D');
        $this->addSql('DROP INDEX IDX_B1D444D745A0AD45 ON call_signal');
        $this->addSql('ALTER TABLE call_signal CHANGE payload payload LONGTEXT DEFAULT NULL COLLATE `utf8mb4_bin`, CHANGE created_at created_at DATETIME NOT NULL');
        $this->addSql('ALTER TABLE call_signal RENAME INDEX idx_b1d444d7f624b39d TO IDX_CALL_SIGNAL_SENDER');
        $this->addSql('ALTER TABLE chat_group DROP FOREIGN KEY FK_6CBDA95E7E3C61F9');
        $this->addSql('ALTER TABLE chat_group_join_request DROP FOREIGN KEY FK_FA9EE464CA760E77');
        $this->addSql('ALTER TABLE chat_group_join_request DROP FOREIGN KEY FK_FA9EE464ED442CF4');
        $this->addSql('ALTER TABLE chat_group_join_request DROP FOREIGN KEY FK_FA9EE464FC6B21F1');
        $this->addSql('ALTER TABLE chat_group_member DROP FOREIGN KEY FK_5D894B29CA760E77');
        $this->addSql('ALTER TABLE chat_group_member DROP FOREIGN KEY FK_5D894B29A76ED395');
        $this->addSql('ALTER TABLE chat_group_message DROP FOREIGN KEY FK_AAFC3CACCA760E77');
        $this->addSql('ALTER TABLE chat_group_message DROP FOREIGN KEY FK_AAFC3CACF624B39D');
        $this->addSql('ALTER TABLE chat_group_message DROP FOREIGN KEY FK_AAFC3CACC76F1F52');
        $this->addSql('ALTER TABLE chat_group_message DROP FOREIGN KEY FK_AAFC3CACFFDF7169');
        $this->addSql('ALTER TABLE chat_group_message CHANGE meta meta LONGTEXT NOT NULL COLLATE `utf8mb4_bin`');
        $this->addSql('ALTER TABLE chat_group_message_reaction DROP FOREIGN KEY FK_41BC1778537A1329');
        $this->addSql('ALTER TABLE chat_group_message_reaction DROP FOREIGN KEY FK_41BC1778A76ED395');
        $this->addSql('ALTER TABLE chat_group_recommendation DROP FOREIGN KEY FK_D18764AFCA760E77');
        $this->addSql('ALTER TABLE chat_group_recommendation DROP FOREIGN KEY FK_D18764AFD59A4918');
        $this->addSql('ALTER TABLE chat_group_recommendation DROP FOREIGN KEY FK_D18764AF4F482379');
        $this->addSql('ALTER TABLE chat_test_message CHANGE settings_snapshot settings_snapshot LONGTEXT NOT NULL COLLATE `utf8mb4_bin`');
        $this->addSql('ALTER TABLE chat_typing_state DROP FOREIGN KEY FK_328D94529AC0396');
        $this->addSql('ALTER TABLE chat_typing_state DROP FOREIGN KEY FK_328D9452A76ED395');
        $this->addSql('DROP INDEX IDX_328D94529AC0396 ON chat_typing_state');
        $this->addSql('ALTER TABLE chat_typing_state CHANGE typing typing TINYINT(1) DEFAULT 0 NOT NULL, CHANGE updated_at updated_at DATETIME NOT NULL');
        $this->addSql('CREATE INDEX IDX_CHAT_TYPING_UPDATED ON chat_typing_state (updated_at)');
        $this->addSql('ALTER TABLE chat_typing_state RENAME INDEX idx_328d9452a76ed395 TO IDX_CHAT_TYPING_USER');
        $this->addSql('ALTER TABLE company_kyc_case DROP FOREIGN KEY FK_E4AB80E7979B1AD6');
        $this->addSql('ALTER TABLE company_kyc_case DROP FOREIGN KEY FK_E4AB80E7FC6B21F1');
        $this->addSql('ALTER TABLE company_kyc_document DROP FOREIGN KEY FK_73C7CC1AA9BA5942');
        $this->addSql('ALTER TABLE company_kyc_review DROP FOREIGN KEY FK_687B158AA9BA5942');
        $this->addSql('ALTER TABLE company_kyc_review DROP FOREIGN KEY FK_687B158A70574616');
        $this->addSql('ALTER TABLE contact_log DROP FOREIGN KEY FK_720509FDA76ED395');
        $this->addSql('ALTER TABLE contact_log DROP FOREIGN KEY FK_720509FD6C066AFE');
        $this->addSql('ALTER TABLE contact_log RENAME INDEX idx_720509fd700047d2 TO IDX_CONTACT_LOG_TICKET');
        $this->addSql('ALTER TABLE contact_ticket RENAME INDEX idx_7329a22fdef8996 TO IDX_CONTACT_TICKET_PROFESSION');
        $this->addSql('ALTER TABLE contact_ticket RENAME INDEX idx_7329a22a76ed395 TO IDX_CONTACT_TICKET_USER');
        $this->addSql('ALTER TABLE contact_ticket RENAME INDEX uniq_7329a224c3a3bb TO UNIQ_CONTACT_TICKET_PAYMENT');
        $this->addSql('ALTER TABLE conversation DROP FOREIGN KEY FK_8A8E26E9EF6A4166');
        $this->addSql('ALTER TABLE conversation DROP FOREIGN KEY FK_8A8E26E9FDDFEE88');
        $this->addSql('ALTER TABLE conversation DROP FOREIGN KEY FK_8A8E26E9FB976A01');
        $this->addSql('ALTER TABLE deliverable DROP FOREIGN KEY FK_A17DA4417E3C61F9');
        $this->addSql('ALTER TABLE deliverable DROP FOREIGN KEY FK_A17DA441C69DE5E5');
        $this->addSql('ALTER TABLE document_access_grant DROP FOREIGN KEY FK_8D753B6E7E3C61F9');
        $this->addSql('ALTER TABLE document_access_grant DROP FOREIGN KEY FK_8D753B6E6C59C752');
        $this->addSql('DROP INDEX IDX_8D753B6E7E3C61F9 ON document_access_grant');
        $this->addSql('DROP INDEX IDX_8D753B6E6C59C752 ON document_access_grant');
        $this->addSql('ALTER TABLE document_access_grant CHANGE status status VARCHAR(20) DEFAULT \'pending\' NOT NULL, CHANGE requested_at requested_at DATETIME NOT NULL, CHANGE decided_at decided_at DATETIME DEFAULT NULL, CHANGE expires_at expires_at DATETIME DEFAULT NULL, CHANGE last_access_at last_access_at DATETIME DEFAULT NULL');
        $this->addSql('CREATE INDEX idx_document_grant_owner_status ON document_access_grant (owner_id, status)');
        $this->addSql('CREATE INDEX idx_document_grant_viewer_status ON document_access_grant (viewer_id, status)');
        $this->addSql('ALTER TABLE email_verifications DROP FOREIGN KEY FK_7EB1F4EEA76ED395');
        $this->addSql('ALTER TABLE favori_job DROP FOREIGN KEY FK_2695B255A76ED395');
        $this->addSql('ALTER TABLE favori_job DROP FOREIGN KEY FK_2695B255BE04EA9');
        $this->addSql('ALTER TABLE favorite DROP FOREIGN KEY FK_68C58ED9A76ED395');
        $this->addSql('ALTER TABLE favorite DROP FOREIGN KEY FK_68C58ED96C066AFE');
        $this->addSql('ALTER TABLE friendship DROP FOREIGN KEY FK_7234A45FED442CF4');
        $this->addSql('ALTER TABLE friendship DROP FOREIGN KEY FK_7234A45F2261B4C3');
        $this->addSql('ALTER TABLE friendship DROP FOREIGN KEY FK_7234A45F1DA661F8');
        $this->addSql('ALTER TABLE incident DROP FOREIGN KEY FK_3D03A11AA76ED395');
        $this->addSql('ALTER TABLE incident CHANGE status status VARCHAR(20) DEFAULT \'open\' NOT NULL, CHANGE severity severity VARCHAR(20) DEFAULT \'error\' NOT NULL, CHANGE trace trace LONGTEXT DEFAULT NULL COLLATE `utf8mb4_bin`, CHANGE context context LONGTEXT DEFAULT NULL COLLATE `utf8mb4_bin`, CHANGE occurrence_count occurrence_count INT DEFAULT 1 NOT NULL, CHANGE created_at created_at DATETIME NOT NULL, CHANGE last_occurred_at last_occurred_at DATETIME NOT NULL, CHANGE resolved_at resolved_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE incident RENAME INDEX idx_3d03a11aa76ed395 TO IDX_INCIDENT_USER');
        $this->addSql('ALTER TABLE incident RENAME INDEX uniq_3d03a11aaea34913 TO UNIQ_INCIDENT_REFERENCE');
        $this->addSql('ALTER TABLE invoices DROP FOREIGN KEY FK_6A2F2F95A76ED395');
        $this->addSql('ALTER TABLE invoices DROP FOREIGN KEY FK_6A2F2F954C3A3BB');
        $this->addSql('ALTER TABLE job DROP FOREIGN KEY FK_FBD8E0F86BF700BD');
        $this->addSql('ALTER TABLE job DROP FOREIGN KEY FK_FBD8E0F828372591');
        $this->addSql('ALTER TABLE job DROP FOREIGN KEY FK_FBD8E0F8FDEF8996');
        $this->addSql('ALTER TABLE job DROP FOREIGN KEY FK_FBD8E0F8B03A8386');
        $this->addSql('ALTER TABLE job DROP FOREIGN KEY FK_FBD8E0F869F4B775');
        $this->addSql('ALTER TABLE job DROP FOREIGN KEY FK_FBD8E0F838E2DD21');
        $this->addSql('ALTER TABLE job ADD urgence_job_id INT DEFAULT NULL, CHANGE created_by_id created_by_id INT DEFAULT NULL');
        $this->addSql('CREATE INDEX IDX_FBD8E0F845E283F4 ON job (urgence_job_id)');
        $this->addSql('ALTER TABLE job_view DROP FOREIGN KEY FK_7931DDCFA76ED395');
        $this->addSql('ALTER TABLE job_view DROP FOREIGN KEY FK_7931DDCFBE04EA9');
        $this->addSql('ALTER TABLE kyc_rule CHANGE meta meta LONGTEXT DEFAULT NULL COLLATE `utf8mb4_bin`');
        $this->addSql('ALTER TABLE message DROP FOREIGN KEY FK_B6BD307F9AC0396');
        $this->addSql('ALTER TABLE message DROP FOREIGN KEY FK_B6BD307FF624B39D');
        $this->addSql('ALTER TABLE message DROP FOREIGN KEY FK_B6BD307FFFDF7169');
        $this->addSql('ALTER TABLE message CHANGE meta meta LONGTEXT DEFAULT NULL COLLATE `utf8mb4_bin`');
        $this->addSql('ALTER TABLE message_reaction DROP FOREIGN KEY FK_ADF1C3E6537A1329');
        $this->addSql('ALTER TABLE message_reaction DROP FOREIGN KEY FK_ADF1C3E6A76ED395');
        $this->addSql('ALTER TABLE newsletter_subscriber CHANGE email email VARCHAR(191) NOT NULL');
        $this->addSql('CREATE INDEX IDX_ALERT_ACTIVE_PROFESSION ON newsletter_subscriber (is_active, profession_id)');
        $this->addSql('ALTER TABLE newsletter_subscriber RENAME INDEX idx_401562c3fdef8996 TO IDX_ALERT_PROFESSION');
        $this->addSql('ALTER TABLE newsletter_subscriber RENAME INDEX idx_401562c3a76ed395 TO IDX_ALERT_USER');
        $this->addSql('ALTER TABLE notification DROP FOREIGN KEY FK_BF5476CAA76ED395');
        $this->addSql('ALTER TABLE payment DROP FOREIGN KEY FK_6D28840DA76ED395');
        $this->addSql('ALTER TABLE payment DROP FOREIGN KEY FK_6D28840D9A1887DC');
        $this->addSql('ALTER TABLE payment DROP FOREIGN KEY FK_6D28840DA53A8AA');
        $this->addSql('ALTER TABLE payment DROP FOREIGN KEY FK_6D28840D590473D');
        $this->addSql('ALTER TABLE payment_dispute DROP FOREIGN KEY FK_25DB5EEDA76ED395');
        $this->addSql('ALTER TABLE payment_dispute DROP FOREIGN KEY FK_25DB5EED4C3A3BB');
        $this->addSql('ALTER TABLE payment_dispute DROP FOREIGN KEY FK_25DB5EED2989F1FD');
        $this->addSql('ALTER TABLE payment_dispute DROP FOREIGN KEY FK_25DB5EEDFE65AF40');
        $this->addSql('ALTER TABLE personal_profile DROP FOREIGN KEY FK_270A324448F3B3C');
        $this->addSql('ALTER TABLE personal_profile DROP FOREIGN KEY FK_270A324A76ED395');
        $this->addSql('ALTER TABLE personal_profile DROP FOREIGN KEY FK_270A324DEF31FA3');
        $this->addSql('ALTER TABLE plan CHANGE features features LONGTEXT DEFAULT NULL COLLATE `utf8mb4_bin`');
        $this->addSql('ALTER TABLE plan_duration DROP FOREIGN KEY FK_883AB7BAE899029B');
        $this->addSql('ALTER TABLE profession DROP FOREIGN KEY FK_BA930D69BCF5E72D');
        $this->addSql('ALTER TABLE professional_media DROP FOREIGN KEY FK_B551BE6FB976A01');
        $this->addSql('ALTER TABLE professional_profile DROP FOREIGN KEY FK_E728A82FDEF8996');
        $this->addSql('ALTER TABLE professional_profile DROP FOREIGN KEY FK_E728A82CDA9F63E');
        $this->addSql('ALTER TABLE professional_profile DROP FOREIGN KEY FK_E728A82A76ED395');
        $this->addSql('ALTER TABLE professional_profile DROP FOREIGN KEY FK_E728A8269F4B775');
        $this->addSql('ALTER TABLE professional_profile_profession_skill DROP FOREIGN KEY FK_6E2CE0BAFB976A01');
        $this->addSql('ALTER TABLE professional_profile_profession_skill DROP FOREIGN KEY FK_6E2CE0BAFDEF8996');
        $this->addSql('ALTER TABLE profile_view DROP FOREIGN KEY FK_4835241A6C59C752');
        $this->addSql('ALTER TABLE profile_view DROP FOREIGN KEY FK_4835241AFB976A01');
        $this->addSql('ALTER TABLE rating DROP FOREIGN KEY FK_D8892622A76ED395');
        $this->addSql('ALTER TABLE rating DROP FOREIGN KEY FK_D889262237F12F38');
        $this->addSql('ALTER TABLE report DROP FOREIGN KEY FK_C42F7784E1CFE6F5');
        $this->addSql('ALTER TABLE report DROP FOREIGN KEY FK_C42F77846C066AFE');
        $this->addSql('ALTER TABLE report DROP FOREIGN KEY FK_C42F7784FE65AF40');
        $this->addSql('ALTER TABLE report DROP FOREIGN KEY FK_C42F7784BCF5E72D');
        $this->addSql('ALTER TABLE report_job DROP FOREIGN KEY FK_B23987FBE04EA9');
        $this->addSql('ALTER TABLE report_job DROP FOREIGN KEY FK_B23987FA76ED395');
        $this->addSql('ALTER TABLE report_job DROP FOREIGN KEY FK_B23987FBCF5E72D');
        $this->addSql('ALTER TABLE review DROP FOREIGN KEY FK_794381C6F675F31B');
        $this->addSql('ALTER TABLE review DROP FOREIGN KEY FK_794381C6158E0B66');
        $this->addSql('ALTER TABLE review DROP FOREIGN KEY FK_794381C6BE04EA9');
        $this->addSql('ALTER TABLE review_score DROP FOREIGN KEY FK_21171B4A3E2E969B');
        $this->addSql('ALTER TABLE review_score DROP FOREIGN KEY FK_21171B4A990BEA15');
        $this->addSql('ALTER TABLE role_definition_permission DROP FOREIGN KEY FK_1672C7AC5EEF6182');
        $this->addSql('ALTER TABLE role_definition_permission DROP FOREIGN KEY FK_1672C7AC7730B2D4');
        $this->addSql('ALTER TABLE sanction DROP FOREIGN KEY FK_6D6491AFA76ED395');
        $this->addSql('ALTER TABLE sanction DROP FOREIGN KEY FK_6D6491AFB03A8386');
        $this->addSql('ALTER TABLE security_event DROP FOREIGN KEY FK_D712E90DA76ED395');
        $this->addSql('ALTER TABLE security_event DROP FOREIGN KEY FK_D712E90D6713A32B');
        $this->addSql('ALTER TABLE security_event CHANGE payload_json payload_json LONGTEXT DEFAULT NULL COLLATE `utf8mb4_bin`');
        $this->addSql('ALTER TABLE security_incident DROP FOREIGN KEY FK_5E6826C8A76ED395');
        $this->addSql('ALTER TABLE security_incident DROP FOREIGN KEY FK_5E6826C8F4BD7827');
        $this->addSql('ALTER TABLE security_incident CHANGE metadata metadata LONGTEXT DEFAULT NULL COLLATE `utf8mb4_bin`');
        $this->addSql('ALTER TABLE subscription DROP FOREIGN KEY FK_A3C664D3A76ED395');
        $this->addSql('ALTER TABLE subscription DROP FOREIGN KEY FK_A3C664D3E899029B');
        $this->addSql('ALTER TABLE subscription DROP FOREIGN KEY FK_A3C664D36BF700BD');
        $this->addSql('ALTER TABLE support_ticket DROP FOREIGN KEY FK_1F5A4D53BBB3772B');
        $this->addSql('ALTER TABLE support_ticket DROP FOREIGN KEY FK_1F5A4D53F4BD7827');
        $this->addSql('ALTER TABLE talent_availability DROP FOREIGN KEY FK_D0C49398FB976A01');
        $this->addSql('ALTER TABLE user DROP FOREIGN KEY FK_8D93D64946032730');
        $this->addSql('ALTER TABLE user DROP FOREIGN KEY FK_8D93D649F92F3E70');
        $this->addSql('ALTER TABLE user CHANGE roles roles LONGTEXT NOT NULL COLLATE `utf8mb4_bin`');
        $this->addSql('ALTER TABLE user RENAME INDEX uniq_8d93d649571323f9 TO uniq_user_apple_id');
        $this->addSql('ALTER TABLE user RENAME INDEX uniq_8d93d6499be8fd98 TO uniq_user_facebook_id');
        $this->addSql('ALTER TABLE user RENAME INDEX uniq_8d93d64944f23b3e TO uniq_user_microsoft_id');
        $this->addSql('ALTER TABLE user_activity_log DROP FOREIGN KEY FK_7DCA8A45A76ED395');
        $this->addSql('ALTER TABLE user_activity_log CHANGE meta meta LONGTEXT NOT NULL COLLATE `utf8mb4_bin`');
        $this->addSql('ALTER TABLE user_log DROP FOREIGN KEY FK_6429094EA76ED395');
        $this->addSql('ALTER TABLE user_log DROP FOREIGN KEY FK_6429094E4FFA550E');
        $this->addSql('ALTER TABLE user_log DROP FOREIGN KEY FK_6429094EA391D4AD');
        $this->addSql('ALTER TABLE user_log DROP FOREIGN KEY FK_6429094E4C9BF8BD');
        $this->addSql('ALTER TABLE user_log DROP FOREIGN KEY FK_6429094EF92F3E70');
        $this->addSql('ALTER TABLE user_setting DROP FOREIGN KEY FK_C779A692A76ED395');
        $this->addSql('ALTER TABLE user_setting CHANGE notifications notifications LONGTEXT NOT NULL COLLATE `utf8mb4_bin`');
        $this->addSql('ALTER TABLE user_two_factor DROP FOREIGN KEY FK_AF21438EA76ED395');
        $this->addSql('ALTER TABLE user_two_factor CHANGE backup_codes backup_codes LONGTEXT DEFAULT NULL COLLATE `utf8mb4_bin`');
        $this->addSql('ALTER TABLE watchlist_item DROP FOREIGN KEY FK_1DEA83F66C066AFE');
        $this->addSql('ALTER TABLE watchlist_item DROP FOREIGN KEY FK_1DEA83F6B03A8386');
        $this->addSql('ALTER TABLE webhook_delivery DROP FOREIGN KEY FK_C97B6A3821AF7E36');
    }
}
